# Generated by Django 3.2.12 on 2023-06-28 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A1', '0007_alter_contact_us_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact_us',
            name='query',
            field=models.TextField(max_length=150),
        ),
    ]
