# Generated by Django 3.2.12 on 2023-06-28 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A1', '0009_alter_contact_us_query'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact_us',
            name='query',
        ),
    ]
