# Generated by Django 3.2.12 on 2023-06-28 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A1', '0010_remove_contact_us_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='query',
            field=models.TextField(null=True),
        ),
    ]
